### ISSUE TITLE
hyde --init loses current directory or something similar

### ISSUE THREAD

**Issue by ffagerho** [hyde/hyde-old#20]
When running hyde --init, the files and directories are created in the current directory, but not visible before cd'ing out and into directory again. Presumably, the current directory is somehow lost or there is some other problem with file system object creation.

I can provide an strace if needed, but I can't seem to find a way to attach files here so I won't do so now.

**Comment by solsticedhiver** [comment]
for me it's not a problem with _hyde_ but a problem with your **shell**. I see this here with bash.

Try this:
    $ cd /tmp
    $ mkdir test
    $ cd test
    $ touch test1
    $ ls
         test1
in **another terminal/shell**
    $ cd /tmp
    $ rm -rf test
    $ mkdir test
    $ touch test2
    $ ls
        test2
then go back to **your first terminal** and type
    $ ls
you will see nothing
because you need to do this
    $ cd ..
    $ cd test
or shorter is to use
    $ cd .
and then
    $ ls
        test2
and you will see your newly created file.

this happens because _hyde_ delete the current empty directory and then recreate it to populate it. This is not _hyde_'s fault. but the shell. it could be avoided if _hyde_ did not delete the empty directory (which is quite useless)

you could use that patch to make it not remove the empty dir:
    diff --git a/hydeengine/**init**.py b/hydeengine/**init**.py
    index aacab7c..a427d73 100644
    --- a/hydeengine/**init**.py 
    +++ b/hydeengine/**init**.py
    @@ -466,7 +466,5 @@ class Initializer(object):
                 if len(files) and not force:
                     raise ValueError(
                     "The site_path[%s] is not empty." % self.site_path)
    -            else:
    -                self.site_path.delete()
             self.site_path.make()
             self.site_path.copy_contents_of(template_dir)

beware that hidden file beginning with a dot could be there and will stay there until you remove them

**Comment by ffagerho** [comment]
You're right, the cause is that hyde deletes the current directory. After that, the shell is in fact in a nonexistent directory and the rest of the observed behaviour is to be expected. So the bug report was not very good, sorry about that.

But why does hyde delete the current directory? It doesn't make sense. If I say hyde --init in an empty directory, I don't see why hyde would have any need to delete the directory. It also makes no sense from the code logic perspective -- if the directory is empty, then just use it.

I guess the logic needs to be updated a bit to handle the case where the site path did not exist.

**Comment by navilan** [comment]
You guys are right. Its stupid to delete a directory when its empty. Will fix it.

**Comment by navilan** [comment]
Fixed.
