### ISSUE TITLE
What is the correct way to create contextual navigation for within a module rather than just a node?

### ISSUE THREAD

**Issue by chetan51** [hyde/hyde-old#39]
When creating contextual navigation for a page, the wiki says to use `page.next` and `page.prev` to get the next and previous pages within the node that the page belongs to. But I have a blog layout like this:

```
blog
    - 2010
        - 9
            - 6
                - article1.html
        - 10
            - 9
                - article2.html
```

And I need the contextual navigation for `article1` to point its next article to `article2`. `page.next` will give me `null` because there are no other articles in the `blog/2010/9/6` node.

How should I go about doing this? Thanks!

**Comment by navilan** [comment]
Chetan,

This is by design. See ContentNode.sort function in siteinfo.py. 

If you want a different behavior, you can add a preprocessor to flatten the context navigation. You can use the walk_pages function in Node to assign the context navigation.

Also, for questions like this you can use - http://groups.google.com/group/hyde-dev. You may get a quicker response from other users.

Thanks
Lakshmi.
